### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by davesnx** [davesnx/postureo.io#2]
- [x] Debug Unhandled rejection WriteError
- [x]  Finish the loop correctly
- [x]  Write some README.md
- [x]  Create method to like media items https://github.com/mckelvey/instagram-node-lib
- [x]  Define the limitations and create the jobs
- [x]  Implement setTimeouts with the jobs
- [ ]  Add tests with AVA.js or mocha
- [ ]  Create a endpoint to recieve the userId and do the loops
- [ ]  Deploy it into heroku
